pr:
  autoCancel: "true"
  branches:
    include:
    - dev
    - qa
    - preprod
    - hotfix
    - main
  paths:
    exclude:
    - README.md
    - azure-pipelines.yml
stages:
- stage: salesforceDemo
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))
  jobs:
  - job: DeployDevOrg
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '14.x'
          checkLatest: true
      - bash: 
          npm install sfdx-cli --global
        displayName: Install Salesforce CLI
      - bash:
            sfdx config:set restDeploy=false --global
        displayName: Use SOAP API for Deployment
      - bash:
            sfdx force:auth:jwt:grant --clientid 3MVG91oqviqJKoEHB897n0v9kXKdE_1tYXPw.BN7Y7JKYPUrsJpt_IqHK4zOMX3ac_GynJK2IsOyX0L6VLdah --jwtkeyfile ./bin/server.key --username reediiiw@resourceful-bear-uxcmex.com --instanceurl https://resourceful-bear-uxcmex-dev-ed.trailblaze.lightning.force.com/
        displayName: Authorize Salesforce DeployDevOrg Org
      - bash:
            sfdx force:source:deploy -p force-app -w 10 -u reediiiw@resourceful-bear-uxcmex.com
        displayName: Deploy source code to DeployDevOrg Org